export const metadata = {
    title: 'My App',
    description: 'Generated by Next.js',
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>
          <nav style={{ padding: '0.1rem', background: '#eee' }}>My Navbar</nav>
          {children}
          <footer style={{ padding: '1rem', background: '#eee' }}>My Footer</footer>
        </body>
      </html>
    );
  }
  